env: "local"

smtp_config:
  host: "mail.hosting.reg.ru"
  port: 587
  username: "support@dm-trade.pro"
  password: "UJ9-EF8-9VP-ae6"

order_info:
  recipient: "serdfhdh@gmail.com"
  subject: "Новый заказ"
  template: "order_template.html"

kafka_config:
  bootstrap_servers: ["192.168.0.2:9092"]
  topics: ["order","password_reset"]
  consumer_group: "email_service"
